* Conditional Random Fields as Recurrent Neural Networks
  https://arxiv.org/pdf/1502.03240.pdf
  MRF/CRF URL :　http://randomfield.cs.waseda.ac.jp/files/saito.pdf
http://sinhrks.hatenablog.com/entry/2014/12/27/232506



  * アブストラクト
    セマンティックセグメンテーションなどのピクセルレベルのラベリングタスクは、画像の理解において中心的な役割を果たします。
    最近のアプローチでは、画像認識のための深層学習技術の機能を利用してピクセルレベルのラベリングタスクに取り組んでいます。
    この方法論の中心的な問題の一つは、視覚オブジェクトの輪郭を描く深層学習手法の能力が限られていることです。
    この問題を解決するために、CNNとCRFベースの確率論的モデリングの長所を組み合わせた新しい形式の畳込みニューラルネットワークを紹介します。
    この目的のために、
    RNNとしてガウスペアワイズポテンシャルを利用した条件付き確率場の平均場近似推論を定式化します。
    次に、CRF-RNNと呼ばれるこのネットワークは、CNNの一部としてプラグインされ、CNNとCRFの重宝の望ましいプロパティを持つ深層学習ネットワークを取得できる。
    重要なのは、私達のシステムがCRFモデリングをCNNと完全に統合し、通常のバックプロパゲーションアルゴリズムを使用して深層学習ネットワークをEND-toーENDでトレーニングできるようにし、
    オブジェクト描写のためのオフライン後処理方法を回避することです。

  * introduction
    現在のセメンティックセグメンテーションは大きな課題がある。
    従来のCNNには大きな受信フィールド（かなり抽象化される）を持つ畳み込みフィルターがあるため、再構築すると荒い出力が生成される。
    CNNにマックスプーリング層が存在すると細かいセグメンテーション出力を得られる可能性は更に低くなる。
    次に、CNNには類似ピクセル感のラベルの一致、およびラベル付け出力の外観の一貫性を促進する滑らかさの制約がない。
    このような滑らかさの制約がないとセグメンテーション出力でオブジェクトの描写が不十分になる。

    深層学習とはべつの道でCRFが開発された。これはピクセルレベルのラベリングタスクの精度を高めらうための効果的な方法として運用されている。
    特にマルコフ確率場（MRF）とその変形条件付き確率場（CRF）はこの分野で広く成功を収めており、コンピュータビジョンで使用される最も成功したモデルの一つとなっています。
    セマンティックラベルのためのCRF推論の重要なアイデアは、類似したピクセル間のラベルの一致などの過程を組み込んだ確率的推論問題として問題を定式化することです。
    CRF推論は、弱くて粗いピクセルレベルのラベル予測を洗練して、鋭い協会ときめ細かいセグメンテーションを生成することができる。
    したがって、直感的にCRFを使用してピクセルレベルのラベリングタスクにCNNを利用する際の欠点を克服できる。

    CRFを利用してセマンティックレベリングを改善する一つの方法はCNNのトレーニングから切り離されたあと処理ステップとしてCRF推論を適用することである。
    しかし。深層学習ネットワークと結合されていないため、CEFの強度を十分に活用していない。
    この設定では深層学習ネットワークはトレーニングフェーズ中にCRFを認識しない。

    この論文ではピクセルレベルのセマンティック画像のセグメンテーション問題のEND-to-ENDの深い学習ソリューションを提案する。
    私達の定式化はCNNとCRFベースのモデルの長所を一つに統一させたフレームワークに組み合わせています。
    より具体的には、トレーニング中に誤差をCNNに戻しながら、フォワードパスで従来のCNNからの粗い出力を更新できるRNNとして、ガウシアンペアワイズポテンシャルを持つ高密度CRFの平均フィールド近似推論を定式化します。
    重要なのは、私達の公式では従来のCNNとCRF推論用のRNNで構成される深層学習ネットワーク全体を通常のバックプロパゲーションアルゴリズムをしようしてEND-to-ENDでトレーニングできることです。

 * Conditional Random Fields
   このセクションでは、ピクセル単位のラベリングのための条件付き確率場（CRF）の概要を説明し、この論文で使用されている表記法を紹介する。
   ピクセル単位のラベル予測のコンテキストで使用されるCRFは、グローバルな観測を条件としてマルコフ確率（MRF）を形成する確率変数としてピクセルラベルをモデル化します。
   ・・・・この先は難しくてよくわからん

 * Structure of CNN
   この論文の重要な部分は、平均場CRF推論がRNNとして最定式化できることを示すことです。
   この目的のために、最初にアルゴリズムに要約されている平均場アルゴリズムのここのステップを検討し、それらをCNN層として説明する。
   トレーニング段階のあとにフィルターが肯定されているCNNの標準畳込み層とは異なり、エッジ保存ガウスフィルタを使用します。
   このフィルターの係数は画像のもとの空間情報と外観情報に依存します。
   これらのフィルターには追加の利点がある。フィルタサイズが画像と同じくらい大きい可能性があるにもかかわらず、必要なパラメータのセットが少なくて済む。
   推論アルゴリズムのステップをCNNレイヤーとして最定式化する一方で、各レイヤーの誤差を計算できることが不可欠。
   トレーニング中のエラーの微分を前のレイヤーに逆伝播できるようにするための入力。また、各層のパラメータに関する誤差を計算する方法についても説明します。
   これにより、バックプロパゲーションアルゴリズムによる最適化が可能になります。
   したがって、私達の定式化では、ガウスカーネルの重みやレベル互換性関数などのCRFパラメータも完全なネットワークのトレーニング中に自動的に最適化できます。
   
 * メッセージパッシング
   密なCRFの定式化では、メッセージパッシングはQ値にMガウスフィルターを適用することによって実装されます。
   ガウスフィルター係数は、ピクセルの位置やRGB値などの画像の特徴に基づいて導出されます。
   これは、ピクセルが他のピクセルとどの程度強く関連しているかを反映しています。
   CRFは幸いなことに、高次元のガウスフィルタリングの計算を大幅に高速化するためのいくつかの近似手法が存在します。
   [29]に続いて、Permutohedral格子の単純化[1]を使用します。これは、O（N）時間でフィルター応答を計算できます。ここで、Nisは画像のピクセル数です[1]。

   バックプロパゲーション中、エラー導関数w.r.t. フィルタ入力は、エラーデリバティブw.r.tを送信することによって計算されます。
   フィルタは、同じMGaussianフィルタを介して逆方向に出力します。
   パーミュトヘドラル格子操作に関しては、これは、フォワードパスと同じ方法でパーミュトヘドラル格子を構築し、スプラッティングし、スライスしながら、ブラー段階で分離可能なフィルターの順序を逆にするだけで達成できます。
   したがって、このフィルタリングステージを介した逆伝播もO（N）時間で実行できます。
   [29]に続いて、2つのガウスカーネル、空間カーネルとバイラテラルカーネルを使用します。
   この作業では、簡単にするために、フィルターの帯域幅の値を固定します。
   帯域幅の値が異なる複数の空間カーネルとバイラテラルカーネルを使用して、それらの最適な線形の組み合わせを学習することもできます。 
